language: go
go: 1.4.2

install:
  - go get -v -t ./...

script:
  - go build ./...
  - go test -v ./...

before_deploy:
  - go get github.com/laher/goxc
  - goxc -t -bc="freebsd,amd64 linux,amd64 windows,386 darwin,amd64"
  - goxc -tasks='xc archive' -bc="freebsd,amd64 linux,amd64 windows,386 darwin,amd64" -d .

deploy:
  provider: releases
  api_key:
    secure: JZtn9vEDoRUIy3IlN+OLZzL27QFfkDZbuJhH/l0e1SOO7RqRSA3rdaQ5I8hoWkThMF7i3PvtUoqNxG1TN4NcTioRbelng0uUqcJ7U+XMLdRGvPo1R9iwiFj9WRPPM+xu7xDeBdfPtAxQVvCOgv9Woz+AXn/tWHUUlkkgxBIbamY39PaIxWpxPl6L/uYUMATdUlLQWV+2y4I0maOwPTVFsj+8zy153i2rdzEARan97hztbY/UtEOoXr0LiPfrOIuCwWhcKRXsYFH1ZgBNLfT9KgM7XBcIv0V/PcKa3GlMOUxCILkfeHPIHCwLntEVXvggJIvInja/zy6bBwlcMQHyeHCTp/rJk+pXN2RhZ4wItKWaYyQJ3R/A3JBy6UG6PXto4Ia6QvdYCUCjSAVkyC80fG6N7budIlCHQpO8o0SxAA595YuJBhzjaPHmapkktFUZNeZVmjpzUpo8H3/rVSV09foIxM2eqzQK2dfVYDDQ5T6wOCkWIat8J6aF/mbCZi8VtK3bh5DvHg+0182Vt0xHFPpg6LL30NY5tOAkwUSMl97awZayT7UVGddPhB75kQ1nfbWqGBnwzYXUFHGVuiLp+vL8za64E7lFlEpxrL9c5Co6pBD5gYYQ+4BvCCUmSEtJ21fxXDKq0WVch5lkwXEjoQd57mZOtnfu02plZ5g5UBE=
  file:
    - snapshot/mikoi_darwin_amd64.zip
    - snapshot/mikoi_freebsd_amd64.zip
    - snapshot/mikoi_linux_amd64.tar.gz
    - snapshot/mikoi_windows_386.zip
  on:
    tags: true
    repo: nabeken/mikoi
